apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: beidchen-sf-finetune-rl-eval-06 # JOB_NAME like  <alias>-<pod/mpijob/torchjob>-<p4/g5/r5>-<project>-<task>[-<note>]
  namespace: default
spec:
  elasticPolicy:
    rdzvBackend: c10d
    minReplicas: 1 #<PLACEHOLDER> e.g. 16 #specify the same number in the env var below
    maxReplicas: 1
    maxRestarts: 1
    nProcPerNode: &gpus_per_node 8
    rdzvId: beidchen-sf-finetune-rl-eval-06
  runPolicy:
    ttlSecondsAfterFinished: 180 # give enough time to push any logs
    schedulingPolicy:
      queue: default
      # priorityClass: {{ priority }} # low-priority # high-priority-preempt-lower high-priority-no-preempt default default-preempt-lower low-priority
      minAvailable: 1 # don't schedule until required replicas are available
      scheduleTimeoutSeconds: 172400 # 48 hours
  pytorchReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: Never #OnFailure
      template:
        spec:
          # priorityClassName: {{ priority }}
          # schedulerName: scheduler-plugins-scheduler
          affinity :
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node.kubernetes.io/instance-type
                        operator: In
                        values:
                          - p5en.48xlarge
          tolerations:
            - key: barijit-pro-model-rl-ablations-nnc7
              operator: Equal
              value: "True"
              effect: NoSchedule
          enableServiceLinks: false
          containers:
            - name: pytorch
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
                - name: FI_EFA_USE_DEVICE_RDMA
                  value: '1'
                - name: FI_PROVIDER
                  value: efa
                - name: NCCL_ASYNC_ERROR_HANDLING
                  value: '1'
                - name: NCCL_SOCKET_IFNAME
                  value: eth0
                - name: GLOO_SOCKET_IFNAME
                  value: eth0
                - name: NCCL_PROTO
                  value: simple
                - name: NCCL_PXN_DISABLE
                  value: '0'
                - name: FI_LOG_LEVEL
                  value: warn
                - name: NCCL_AVOID_RECORD_STREAMS
                  value: '1'
                - name: NCCL_P2P_LEVEL
                  value: NVL
                - name: NCCL_CROSS_NIC
                  value: '1'
                - name: NCCL_DEBUG
                  value: TRACE
                - name: TORCH_NCCL_AVOID_RECORD_STREAMS
                  value: '1'
                - name: NCCL_IGNORE_DISABLED_P2P
                  value: '0'
                - name: REGION
                  value: "us-east-1"
              command: ["bash","-c"]
              # ipv6 needs to be disabled otherwise rdvz comm breaks
              args:
                -  >- 
                  echo "Starting job" | tee "/code-fsx/beidchen-sandbox/zmc_jobstartingsigns.log" && 
                  sysctl -w net.ipv6.conf.all.disable_ipv6=1 && 
                  sysctl -w net.ipv6.conf.default.disable_ipv6=1 && 
                  mount -o remount,size=150G /dev/shm && 
                  export PATH=/opt/amazon/efa/bin:$PATH &&
                  export LD_LIBRARY_PATH=/opt/amazon/efa/lib:$LD_LIBRARY_PATH &&
                  export LD_LIBRARY_PATH=/opt/amazon/ofi-nccl/lib/x86_64-linux-gnu:/opt/amazon/ofi-nccl/lib:/opt/aws-ofi-nccl/lib:$LD_LIBRARY_PATH &&
                  export NCCL_NET=OFI &&
                  export FI_PROVIDER=efa &&
                  export FI_EFA_ENABLE_SHM_TRANSFER=1 &&
                  ulimit -l unlimited &&
                  unset NCCL_SOCKET_IFNAME &&
                  export OMP_NUM_THREADS=64 &&
                  export OLMO_SHARED_FS=1 &&
                  export WANDB_API_KEY="4b48dba8c7c02e44280b472407526572480b6d41" &&
                  export WANDB_MODE=online &&
                  export FI_EFA_FORK_SAFE=1 &&
                  export NCCL_BLOCKING_WAIT=1 &&
                  export NCCL_ASYNC_ERROR_HANDLING=1 &&
                  export NCCL_DEBUG=INFO &&
                  export NCCL_DEBUG_SUBSYS=INIT,NET,ENV &&
                  wandb login --relogin $WANDB_API_KEY &&
                  mkdir -p /workspace/wandb &&
                  export WANDB_DIR=/workspace/wandb &&
                  apt-get install zip -y &&
                  cd /workspace &&
                  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &&
                  unzip awscliv2.zip &&
                  ./aws/install &&
                  cd /code-fsx/beidchen-sandbox/VBench &&
                  pip install VBench &&
                  cd .. &&
                  python -m pip install -e detectron2 --no-build-isolation &&
                  pip install setuptools==69.5.1 &&
                  cd VBench &&
                  mkdir -p /workspace/.cache/vbench/ &&
                  export VBENCH_CACHE_DIR=/workspace/.cache/vbench &&
                  mkdir -p /workspace/.cache/vbench/aesthetic_model/emb_reader/ &&
                  wget -O /workspace/.cache/vbench/aesthetic_model/emb_reader/sa_0_4_vit_l_14_linear.pth https://github.com/LAION-AI/aesthetic-predictor/blob/main/sa_0_4_vit_l_14_linear.pth?raw=true &&
                  wget https://huggingface.co/lalala125/AMT/resolve/main/amt-s.pth -P /workspace/.cache/vbench/amt_model &&
                  wget https://huggingface.co/spaces/xinyu1205/recognize-anything/resolve/main/tag2text_swin_14m.pth -P /workspace/.cache/vbench/caption_model &&
                  wget https://openaipublic.azureedge.net/clip/models/40d365715913c9da98579312b702a82c18be219cc2a73407c4526f58eba950af/ViT-B-32.pt -P /workspace/.cache/vbench/clip_model &&
                  wget https://openaipublic.azureedge.net/clip/models/b8cca3fd41ae0c99ba7e8951adf17d267cdb84cd88be6f7c2e0eca1737a03836/ViT-L-14.pt -P /workspace/.cache/vbench/clip_model &&
                  wget https://huggingface.co/OpenGVLab/VBench_Used_Models/resolve/main/grit_b_densecap_objectdet.pth -P /workspace/.cache/vbench/grit_model &&
                  wget https://github.com/chaofengc/IQA-PyTorch/releases/download/v0.1-weights/musiq_spaq_ckpt-358bb6af.pth -P /workspace/.cache/vbench/pyiqa_model &&
                  wget -P /workspace/.cache/vbench/raft_model/ https://dl.dropboxusercontent.com/s/4j4z58wuv8o0mfz/models.zip &&
                  unzip -d /workspace/.cache/vbench/raft_model/ /workspace/.cache/vbench/raft_model/models.zip &&
                  rm -r /workspace/.cache/vbench/raft_model/models.zip &&
                  wget https://huggingface.co/OpenGVLab/VBench_Used_Models/resolve/main/l16_ptk710_ftk710_ftk400_f16_res224.pth -P  /workspace/.cache/vbench/umt_model/ &&
                  wget https://huggingface.co/OpenGVLab/VBench_Used_Models/resolve/main/ViClip-InternVid-10M-FLT.pth -P /workspace/.cache/vbench/ViCLIP &&
                  wget https://raw.githubusercontent.com/openai/CLIP/main/clip/bpe_simple_vocab_16e6.txt.gz -P /workspace/.cache/vbench/ViCLIP &&
                  git clone https://github.com/facebookresearch/dino /workspace/.cache/vbench/dino_model/facebookresearch_dino_main/ &&
                  wget -P /workspace/.cache/vbench/dino_model/dino_vitbase16_pretrain.pth https://dl.fbaipublicfiles.com/dino/dino_vitbase16_pretrain/dino_vitbase16_pretrain.pth &&
                  aws s3 cp s3://agi-mm-training-shared-us-east-2/beidchen/data/wan_fewstep_svg2_vbench_videos /workspace/vbench_videos --region us-east-2 --recursive &&
                  torchrun --nproc_per_node=8 --rdzv-conf="timeout=7200,read_timeout=7200,join_timeout=7200" evaluate.py --output_path /checkpoints-fsx/beidchen-sandbox/vbench_eval_results/wan_fewstep_svg2 --videos_path /workspace/vbench_videos --wandb_name wan_fewstep_svg2 --dimension subject_consistency background_consistency temporal_flickering motion_smoothness dynamic_degree aesthetic_quality imaging_quality object_class multiple_objects human_action color spatial_relationship scene temporal_style appearance_style overall_consistency --mode vbench_standard 2>&1 | tee /code-fsx/beidchen-sandbox/wan_fewstep_svg2_vbench.log
              image: 767397878797.dkr.ecr.us-east-1.amazonaws.com/agif-mm-pt-base:reasoning-vllm.sglang.megatron.deepseek.video.fa3
              imagePullPolicy: Always
              securityContext:
                privileged: true
              resources:
                limits:
                  hugepages-2Mi: 5120Mi
                  vpc.amazonaws.com/efa: 16
                  nvidia.com/gpu: *gpus_per_node
                requests:
                  nvidia.com/gpu: *gpus_per_node
                  vpc.amazonaws.com/efa: 16
                  memory: 15000Mi
                  ephemeral-storage: 32Gi
              volumeMounts:
                - mountPath: /data-fsx
                  name: fsx-claim-general--atl-2a2
                - mountPath: /code-fsx
                  name: fsx-claim-general--atl-2a1
                - mountPath: /checkpoints-fsx
                  name: fsx-claim-general--atl-2a3
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /dev/infiniband/uverbs0
                  name: infiniband-efa-0
                - mountPath: /dev/infiniband/uverbs1
                  name: infiniband-efa-1
                - mountPath: /dev/infiniband/uverbs2
                  name: infiniband-efa-2
                - mountPath: /dev/infiniband/uverbs3
                  name: infiniband-efa-3
                - mountPath: /dev/infiniband/uverbs4
                  name: infiniband-efa-4
                - mountPath: /dev/infiniband/uverbs5
                  name: infiniband-efa-5
                - mountPath: /dev/infiniband/uverbs6
                  name: infiniband-efa-6
                - mountPath: /dev/infiniband/uverbs7
                  name: infiniband-efa-7
                - mountPath: /dev/infiniband/uverbs8
                  name: infiniband-efa-8
                - mountPath: /dev/infiniband/uverbs9
                  name: infiniband-efa-9
                - mountPath: /dev/infiniband/uverbs10
                  name: infiniband-efa-10
                - mountPath: /dev/infiniband/uverbs11
                  name: infiniband-efa-11
                - mountPath: /dev/infiniband/uverbs12
                  name: infiniband-efa-12
                - mountPath: /dev/infiniband/uverbs13
                  name: infiniband-efa-13
                - mountPath: /dev/infiniband/uverbs14
                  name: infiniband-efa-14
                - mountPath: /dev/infiniband/uverbs15
                  name: infiniband-efa-15
          volumes:
            - name: fsx-claim-general--atl-2a1
              persistentVolumeClaim:
                claimName: fsx-claim-general--atl-2a1
            - name: fsx-claim-general--atl-2a2
              persistentVolumeClaim:
                claimName: fsx-claim-general--atl-2a2
            - name: fsx-claim-general--atl-2a3
              persistentVolumeClaim:
                claimName: fsx-claim-general--atl-2a3
            - name: infiniband-efa-0
              hostPath:
                path: /dev/infiniband/uverbs0
            - name: infiniband-efa-1
              hostPath:
                path: /dev/infiniband/uverbs1
            - name: infiniband-efa-2
              hostPath:
                path: /dev/infiniband/uverbs2
            - name: infiniband-efa-3
              hostPath:
                path: /dev/infiniband/uverbs3
            - name: infiniband-efa-4
              hostPath:
                path: /dev/infiniband/uverbs4
            - name: infiniband-efa-5
              hostPath:
                path: /dev/infiniband/uverbs5
            - name: infiniband-efa-6
              hostPath:
                path: /dev/infiniband/uverbs6
            - name: infiniband-efa-7
              hostPath:
                path: /dev/infiniband/uverbs7
            - name: infiniband-efa-8
              hostPath:
                path: /dev/infiniband/uverbs8
            - name: infiniband-efa-9
              hostPath:
                path: /dev/infiniband/uverbs9
            - name: infiniband-efa-10
              hostPath:
                path: /dev/infiniband/uverbs10
            - name: infiniband-efa-11
              hostPath:
                path: /dev/infiniband/uverbs11
            - name: infiniband-efa-12
              hostPath:
                path: /dev/infiniband/uverbs12
            - name: infiniband-efa-13
              hostPath:
                path: /dev/infiniband/uverbs13
            - name: infiniband-efa-14
              hostPath:
                path: /dev/infiniband/uverbs14
            - name: infiniband-efa-15
              hostPath:
                path: /dev/infiniband/uverbs15
            - name: dshm
              emptyDir: 
                medium: Memory
                sizeLimit: 8Gi